# Generated by Django 3.0.7 on 2020-06-08 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_address.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_ADDRESS_ADDRESS_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('delivery_address', django_address.fields.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_ADDRESS_ADDRESS_MODEL, verbose_name='Delivery address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
