stages:
- test
- pages

cache:
  key: ${CI_COMMIT_SHA}
  paths:
  - .venv/

test:
  stage: test
  image: python:3.8.2-alpine3.11
  variables:
    POSTGRES_DB: s1psp
    POSTGRES_USER: s1psp
    POSTGRES_PASSWORD: s1psp
    POSTGRES_HOST: postgres
    PIPENV_VENV_IN_PROJECT: enabled
  services:
  - postgres:11.5-alpine
  before_script:
  - apk add build-base ca-certificates make git postgresql-libs postgresql-dev gcc musl-dev
  - pip install -U pip pipenv
  script:
  - pipenv sync --dev
  - pipenv run black --check .
  - pipenv run flake8
  - pipenv run pytest

pages:
  stage: pages
  image: python:3.8.2-alpine3.11
  when: on_success
  only:
  - master
  variables:
    PIPENV_VENV_IN_PROJECT: enabled
  before_script:
  - apk add build-base ca-certificates make git postgresql-libs postgresql-dev gcc musl-dev
  - pip install -U pip pipenv
  script:
  - cd docs && pipenv run make html
  - mv build/html ../public
  artifacts:
    paths:
      - public
